# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(max_length=10)),
                ('brigade', models.IntegerField(max_length=3)),
                ('last_updated', models.DateTimeField(verbose_name='last updated date')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
