# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brigade',
            field=models.IntegerField(),
        ),
    ]
